spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_master?useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: localhost:20010

server:
  port: 8083
  servlet:
    context-path: /movie-master-api
logging:
  file:
    name: D:/Development/WS/log/local/movie-master-api/movie-master-api.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework: INFO
    org.hibernate: INFO
    org.example.movie.master: INFO
    org.springframework.web: TRACE

kafka:
  movieBookingApi:
    groupName: movie-schedule
    movieDetails:
      topic:
        request: movie-details-request
        response: movie-details-response
        serialization-class: org.example.movie.core.common.schedule.MovieDetailsListRequest